version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20   # Change from 18 to 20 (or latest)
    commands:
      - npm install
  build:
    commands:
      - npm run build

artifacts:
  files:
    - '**/*'
  base-directory: dist
  discard-paths: yes
